language: python

python:
  - '2.7'

before_install:
  - sudo ./install -i
  - sudo ./install -b
  - sudo ./install -r
  - sudo ./install -m
  - sudo ./install

before_script:
  - sudo bin/dpm-start
  - sleep 10

services:
  - mongodb

script:
  - tests/test-dpm
